import pathlib, re, sys
S = pathlib.Path(__file__).parent
src = (S / 'index.js').read_text()
orig_len = len(src)
fails = []

def rep(old, new, count=1, label=None):
    global src
    n = src.count(old)
    if n != count:
        fails.append(f"{label or old[:60]!r}: expected {count}, found {n}")
        return
    src = src.replace(old, new)

V2 = '["google_business_profile", "google_search_organic", "google_ads", "website_direct", "facebook_organic_page", "facebook_group_post", "meta_ads", "facebook_marketplace", "instagram", "nextdoor", "referral", "repeat_customer", "commercial_account", "truck_trailer_signage", "yard_sign_flyer", "other", "unknown", "google", "facebook", "yard_sign", "website"]'
PAY = '["cash", "check", "venmo", "cash_app", "zelle", "stripe_card", "stripe_ach", "bank_transfer", "card", "other"]'

# ---- constants ----
rep('var LEAD_SOURCES = [\n  "google",\n  "facebook",\n  "referral",\n  "yard_sign",\n  "website",\n  "repeat_customer",\n  "other"\n];', f'var LEAD_SOURCES = {V2};', label='LEAD_SOURCES')
rep('var LEAD_SOURCES2 = [\n  "google",\n  "facebook",\n  "referral",\n  "yard_sign",\n  "website",\n  "repeat_customer",\n  "other"\n];', f'var LEAD_SOURCES2 = {V2};', label='LEAD_SOURCES2')
rep('var UPDATABLE_LEAD_SOURCES = [\n  "google", "google_ads", "facebook", "instagram", "referral", "yard_sign",\n  "website", "repeat_customer", "other"\n];', f'var UPDATABLE_LEAD_SOURCES = {V2};', label='UPDATABLE_LEAD_SOURCES')
rep('var PAYMENT_METHODS = ["cash", "venmo", "card", "check", "other"];', f'var PAYMENT_METHODS = {PAY};', label='PAYMENT_METHODS')
rep('var METHODS2 = ["cash", "venmo", "card", "check", "other"];', f'var METHODS2 = {PAY};', label='METHODS2')
rep('  "permits",\n  "misc"\n];\nvar PAID_WITH = ["bluevine", "credit_card", "cash", "other"];',
    '  "permits",\n  "misc",\n  "job_supplies",\n  "crew_meals",\n  "dumpster_rental",\n  "payment_processing",\n  "bank_fees",\n  "vehicle_mileage",\n  "owner_draw",\n  "personal"\n];\nvar EXPENSE_CLASSES = ["direct_job_cost", "overhead", "capital", "owner_draw", "personal"];\nvar PAID_WITH = ["bluevine", "credit_card", "cash", "cash_app", "venmo", "zelle", "other"];', label='EXPENSE_CATEGORIES')
# categorize rules: personal/owner draw/supplies/meals/fees
rep('  { match: /\\b(payroll|wages|helper|labor|cash app|venmo to|zelle to)\\b/i, category: "payroll", weight: 0.6 }\n];',
    '  { match: /\\b(payroll|wages|helper|labor|cash app|venmo to|zelle to)\\b/i, category: "payroll", weight: 0.6 },\n  { match: /\\b(owner pay|paying myself|owner draw|capital one|personal account)\\b/i, category: "owner_draw", weight: 0.85 },\n  { match: /\\b(icloud|hiya|sonic|major tomato|personal)\\b/i, category: "personal", weight: 0.8 },\n  { match: /\\b(jimmy john|coney|mcdonald|wendy|taco bell|subway|crew (meal|food|lunch|breakfast)|ice\\/drinks)\\b/i, category: "crew_meals", weight: 0.8 },\n  { match: /\\b(dumpster|w&d dumpster|roll ?off)\\b/i, category: "dumpster_rental", weight: 0.9 },\n  { match: /\\b(stripe fee|processing fee)\\b/i, category: "payment_processing", weight: 0.9 },\n  { match: /\\b(atm fee|bank fee|overdraft|wire fee)\\b/i, category: "bank_fees", weight: 0.9 }\n];', label='RULES')

# ---- create_expense: classification + bank ref ----
rep('        paid_with: external_exports.enum(PAID_WITH).default("bluevine").describe("Which account/method paid for it")\n      }\n    },\n    guarded(async (a) => {\n      if (a.job_id) {',
    '        paid_with: external_exports.enum(PAID_WITH).default("bluevine").describe("Which account/method paid for it"),\n        expense_class: external_exports.enum(EXPENSE_CLASSES).optional().describe("Defaults from the category: direct_job_cost | overhead | capital | owner_draw | personal. owner_draw and personal stay in the ledger but never count in profit"),\n        bank_txn_ref: external_exports.string().optional().describe("Bank descriptor/ID for duplicate detection, e.g. FACEBK *V2ST66JX24"),\n        is_pending: external_exports.boolean().default(false).describe("Bank charge not yet posted"),\n        campaign_id: external_exports.string().uuid().optional().describe("Marketing campaign this spend belongs to"),\n        asset_id: external_exports.string().uuid().optional().describe("For capital purchases: the asset row"),\n        override_reason: external_exports.string().optional().describe("Only for a manual payroll expense on a job that already has helper hours logged — say why it is not a double count")\n      }\n    },\n    guarded(async (a) => {\n      if (a.job_id) {', label='create_expense schema')
rep('        job_id: a.job_id ?? null,\n        paid_with: a.paid_with,\n        created_by: env.OWNER_USER_ID\n      }).select("id,amount,category,incurred_on,vendor,description,job_id,paid_with").single();\n      if (error51) return fail("db_error", error51.message);\n      return ok({\n        expense_id: data.id,',
    '        job_id: a.job_id ?? null,\n        paid_with: a.paid_with,\n        expense_class: a.expense_class ?? null,\n        bank_txn_ref: a.bank_txn_ref ?? null,\n        is_pending: a.is_pending ?? false,\n        campaign_id: a.campaign_id ?? null,\n        asset_id: a.asset_id ?? null,\n        override_reason: a.override_reason ?? null,\n        created_by: env.OWNER_USER_ID\n      }).select("id,amount,category,incurred_on,vendor,description,job_id,paid_with,expense_class,is_tax_deductible,is_pending,campaign_id").single();\n      if (error51) return fail("db_error", error51.message);\n      return ok({\n        expense_id: data.id,\n        expense_class: data.expense_class,\n        is_tax_deductible: data.is_tax_deductible,\n        is_pending: data.is_pending,', label='create_expense insert')

# ---- bulk_import_expenses: new fields + duplicate guard ----
rep('            job_id: external_exports.string().uuid().optional(),\n            paid_with: external_exports.enum(PAID_WITH).optional()\n          })\n        ).min(1).max(200).describe("Up to 200 rows"),',
    '            job_id: external_exports.string().uuid().optional(),\n            paid_with: external_exports.enum(PAID_WITH).optional(),\n            expense_class: external_exports.enum(EXPENSE_CLASSES).optional(),\n            bank_txn_ref: external_exports.string().optional().describe("Bank descriptor/ID; rows matching an existing expense on it are returned as possible_duplicate, not written"),\n            is_pending: external_exports.boolean().optional(),\n            campaign_id: external_exports.string().uuid().optional()\n          })\n        ).min(1).max(200).describe("Up to 200 rows"),', label='bulk schema')
rep('    guarded(async ({ rows, default_paid_with, dry_run }) => {\n      const written = [];\n      const needsReview = [];\n      const failed = [];\n      for (let i = 0; i < rows.length; i++) {\n        const r = rows[i];\n        try {\n          const amount = r.amount ?? (r.line ? parseAmount(r.line) : null);\n          const incurred = r.incurred_on ?? (r.line ? parseDate(r.line) : null) ?? detroitToday();\n          if (!amount) {\n            needsReview.push({ row: i, line: r.line ?? null, reason: "no amount found" });\n            continue;\n          }',
    '    guarded(async ({ rows, default_paid_with, dry_run }) => {\n      const written = [];\n      const needsReview = [];\n      const failed = [];\n      const possibleDuplicates = [];\n      const since = addDays(rows.reduce((m, r) => { const d = r.incurred_on ?? (r.line ? parseDate(r.line) : null); return d && d < m ? d : m; }, detroitToday()), -3);\n      const { data: recent } = await dbc.from("expenses").select("id,amount,incurred_on,vendor,bank_txn_ref,description").is("deleted_at", null).gte("incurred_on", since);\n      const norm = (s) => String(s ?? "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();\n      const similarVendor = (a, b) => { const x = norm(a), y = norm(b); if (!x || !y) return false; return x === y || x.includes(y) || y.includes(x) || x.split(" ")[0] === y.split(" ")[0]; };\n      const findDupe = (amount, incurred, vendor, ref) => (recent ?? []).find((e) => (ref && e.bank_txn_ref && e.bank_txn_ref === ref) || (Math.abs(Number(e.amount) - amount) <= 0.5 && Math.abs((new Date(e.incurred_on).getTime() - new Date(incurred).getTime()) / 864e5) <= 2 && similarVendor(e.vendor ?? e.description, vendor)));\n      for (let i = 0; i < rows.length; i++) {\n        const r = rows[i];\n        try {\n          const amount = r.amount ?? (r.line ? parseAmount(r.line) : null);\n          const incurred = r.incurred_on ?? (r.line ? parseDate(r.line) : null) ?? detroitToday();\n          if (!amount) {\n            needsReview.push({ row: i, line: r.line ?? null, reason: "no amount found" });\n            continue;\n          }\n          const dupe = findDupe(amount, incurred, r.vendor ?? r.line, r.bank_txn_ref);\n          if (dupe) {\n            possibleDuplicates.push({ row: i, line: r.line ?? null, amount, incurred_on: incurred, matches_expense_id: dupe.id, existing: { amount: Number(dupe.amount), incurred_on: dupe.incurred_on, vendor: dupe.vendor, bank_txn_ref: dupe.bank_txn_ref }, reason: r.bank_txn_ref && dupe.bank_txn_ref === r.bank_txn_ref ? "same bank_txn_ref" : "same amount ±$0.50 within ±2 days, similar vendor" });\n            continue;\n          }', label='bulk dupe')
rep('            job_id: r.job_id ?? null,\n            paid_with: r.paid_with ?? default_paid_with,\n            created_by: env.OWNER_USER_ID\n          }).select("id,amount,category,incurred_on,vendor").single();',
    '            job_id: r.job_id ?? null,\n            paid_with: r.paid_with ?? default_paid_with,\n            expense_class: r.expense_class ?? null,\n            bank_txn_ref: r.bank_txn_ref ?? null,\n            is_pending: r.is_pending ?? false,\n            campaign_id: r.campaign_id ?? null,\n            created_by: env.OWNER_USER_ID\n          }).select("id,amount,category,incurred_on,vendor,expense_class").single();', label='bulk insert')
rep('        needs_review_count: needsReview.length,\n        failed_count: failed.length,',
    '        needs_review_count: needsReview.length,\n        possible_duplicate_count: possibleDuplicates.length,\n        possible_duplicate: possibleDuplicates,\n        failed_count: failed.length,', label='bulk output')

# ---- update_expense ----
rep('        clear_job: external_exports.boolean().optional().describe("true unlinks it from its job (becomes overhead)"),\n        paid_with: external_exports.enum(PAID_WITH).optional()\n      }\n    },',
    '        clear_job: external_exports.boolean().optional().describe("true unlinks it from its job (becomes overhead)"),\n        paid_with: external_exports.enum(PAID_WITH).optional(),\n        expense_class: external_exports.enum(EXPENSE_CLASSES).optional().describe("direct_job_cost | overhead | capital | owner_draw | personal"),\n        is_tax_deductible: external_exports.boolean().optional(),\n        bank_txn_ref: external_exports.string().optional(),\n        is_pending: external_exports.boolean().optional(),\n        campaign_id: external_exports.string().uuid().optional(),\n        asset_id: external_exports.string().uuid().optional(),\n        override_reason: external_exports.string().optional()\n      }\n    },', label='update_expense schema')
rep('.select("id,amount,category,incurred_on,vendor,description,job_id,paid_with").single();\n      if (error51) return fail("db_error", error51.message);\n      await audit(dbc, "update_expense"',
    '.select("id,amount,category,incurred_on,vendor,description,job_id,paid_with,expense_class,is_tax_deductible,is_pending,campaign_id,asset_id").single();\n      if (error51) return fail("db_error", error51.message);\n      await audit(dbc, "update_expense"', label='update_expense select')

# ---- record_payment: method required (already) + processing_fee ----
rep('        method: external_exports.enum(METHODS2).describe("How they paid \\u2014 ask Mico, don\'t assume"),',
    '        method: external_exports.enum(METHODS2).describe("How they paid \\u2014 ask Mico, don\'t assume. cash, check, venmo, cash_app, zelle, stripe_card, stripe_ach, bank_transfer, other"),\n        processing_fee: external_exports.number().min(0).optional().describe("Card/ACH fee taken by the processor; a payment_processing expense is created automatically"),', label='record_payment schema')
rep('        tip: a.tip ?? 0,\n        reference: a.reference ?? null,\n        paid_at: (/* @__PURE__ */ new Date(`${paidOn}T12:00:00Z`)).toISOString(),\n        created_by: env.OWNER_USER_ID\n      });\n      if (payErr) return fail("db_error", payErr.message);',
    '        tip: a.tip ?? 0,\n        processing_fee: a.processing_fee ?? 0,\n        reference: a.reference ?? null,\n        paid_at: (/* @__PURE__ */ new Date(`${paidOn}T12:00:00Z`)).toISOString(),\n        created_by: env.OWNER_USER_ID\n      });\n      if (payErr) return fail("db_error", payErr.message);', label='record_payment insert')

# ---- complete_job: scope fields, owner hours, helper labor, dump allocation ----
rep('        tip: external_exports.number().min(0).optional().describe("Tip the customer added, in dollars. Shows as its own line on the invoice and in reports, on top of final_price"),\n        notes: external_exports.string().optional().describe("Anything worth remembering about the job")\n      }\n    },',
    '        tip: external_exports.number().min(0).optional().describe("Tip the customer added, in dollars. Shows as its own line on the invoice and in reports, on top of final_price"),\n        notes: external_exports.string().optional().describe("Anything worth remembering about the job"),\n        service_type: external_exports.enum(["single_item", "furniture", "appliance", "mattress", "hot_tub", "garage_cleanout", "basement_cleanout", "estate_cleanout", "whole_home_cleanout", "yard_waste", "construction_debris", "demo", "commercial_cleanout", "property_turnover", "other"]).optional().describe("Service line \\u2014 required for a fully costed job"),\n        hauling_unit: external_exports.enum(["truck_bed", "trailer_6x12", "dumpster", "multiple"]).optional(),\n        load_fraction: external_exports.number().min(0).optional().describe("Trailer loads used, e.g. 0.25, 0.5, 1, 2.5"),\n        crew_size: external_exports.number().int().min(1).optional().describe("Total crew including Mico"),\n        mattress_count: external_exports.number().int().min(0).optional(),\n        access_flags: external_exports.array(external_exports.enum(["stairs", "basement", "long_carry", "tight_access", "second_floor", "no_driveway_access"])).optional(),\n        owner_hours: external_exports.number().min(0).optional().describe("Mico\'s hours on this job (logged at $0; drives owner $/hr)"),\n        owner_drive_hours: external_exports.number().min(0).optional(),\n        helper_labor: external_exports.array(external_exports.object({ worker_name: external_exports.string(), hours: external_exports.number().positive(), rate: external_exports.number().min(0).optional(), paid: external_exports.boolean().default(false) })).optional().describe("Helper hours per worker \\u2014 the ONE record of helper pay. paid: true also settles it (payroll expense is generated). Use this instead of crew_cost"),\n        dump_ticket: external_exports.object({ cost: external_exports.number().min(0), site: external_exports.string().optional(), weight_tons: external_exports.number().optional(), paid: external_exports.boolean().optional() }).optional().describe("The dump ticket for this load; use instead of disposal_cost so the site and tonnage are kept"),\n        allocate_ticket_ids: external_exports.array(external_exports.string().uuid()).optional().describe("Existing dump tickets (staged loads) this job was part of"),\n        disposed_at: external_exports.string().optional().describe("When the load was dumped (ISO or YYYY-MM-DD HH:MM Detroit)"),\n        review_requested: external_exports.boolean().optional()\n      }\n    },', label='complete_job schema')
# crew_cost expense needs an explicit override so the labor-entry guard is not silently bypassed
rep('      if (a.crew_cost) expenses.push({ category: "payroll", amount: a.crew_cost, description: "Crew for job" });',
    '      if (a.crew_cost) expenses.push({ category: "payroll", amount: a.crew_cost, description: "Crew for job (lump sum \\u2014 prefer helper_labor)", override_reason: "complete_job crew_cost lump sum" });', label='crew_cost')
rep('          description: `${e.description} \\u2014 ${job.title}`,\n          job_id: job.id,\n          created_by: env.OWNER_USER_ID\n        });\n        if (error51) expenseErrors.push(`${e.category}: ${error51.message}`);\n      }',
    '          description: `${e.description} \\u2014 ${job.title}`,\n          job_id: job.id,\n          override_reason: e.override_reason ?? null,\n          created_by: env.OWNER_USER_ID\n        });\n        if (error51) expenseErrors.push(`${e.category}: ${error51.message}`);\n      }\n      const scope = await applyCloseOutDetails(dbc, env, job.id, a, completedOn, expenseErrors);', label='complete_job scope')
rep('        profit: Math.round((a.final_price - costs) * 100) / 100,\n        ...expenseErrors.length ? { warnings: expenseErrors } : {}\n      });\n    })\n  );\n}\n__name(registerJobWriteTools, "registerJobWriteTools");',
    '        profit: Math.round((a.final_price - costs) * 100) / 100,\n        close_out: scope,\n        still_missing: scope?.still_missing ?? null,\n        ...expenseErrors.length ? { warnings: expenseErrors } : {}\n      });\n    })\n  );\n}\n__name(registerJobWriteTools, "registerJobWriteTools");\n\n// Scope + labor + disposal capture shared by complete_job (both the first close-out and the correction path).\nasync function applyCloseOutDetails(dbc, env, jobId, a, completedOn, warnings) {\n  const p = {};\n  for (const k of ["service_type", "hauling_unit", "load_fraction", "crew_size", "mattress_count", "access_flags", "owner_hours", "owner_drive_hours", "dump_ticket", "allocate_ticket_ids", "review_requested", "disposed_at"]) if (a[k] !== void 0) p[k] = a[k];\n  if (a.disposed_at && /^\\d{4}-\\d{2}-\\d{2}( \\d{2}:\\d{2})?$/.test(a.disposed_at)) p.disposed_at = parseDetroit(a.disposed_at);\n  if (a.dump_ticket) p.dump_ticket = { ...a.dump_ticket, site: a.dump_ticket.site ?? a.disposal_site ?? "Other", dumped_on: completedOn };\n  p.completed_on = completedOn;\n  if (Array.isArray(a.helper_labor)) {\n    for (const h of a.helper_labor) {\n      const r = await resolveWorker(dbc, { worker_name: h.worker_name });\n      if ("error" in r) { warnings.push(`helper_labor ${h.worker_name}: no matching worker (create_worker first)`); continue; }\n      const rate = h.rate ?? Number(r.worker.default_rate);\n      const { data: le, error: leErr } = await dbc.from("labor_entries").insert({ worker_id: r.worker.id, worked_on: completedOn, hours: h.hours, rate, job_id: jobId, activity: "on_job", created_by: env.OWNER_USER_ID }).select("id").single();\n      if (leErr) { warnings.push(`helper_labor ${h.worker_name}: ${leErr.message}`); continue; }\n      if (h.paid) await dbc.from("labor_entries").update({ paid_at: new Date().toISOString() }).eq("id", le.id);\n    }\n  }\n  const { data, error } = await dbc.rpc("job_close_out", { p_job_id: jobId, p });\n  if (error) { warnings.push(`close-out details: ${error.message}`); return null; }\n  return data;\n}\n__name(applyCloseOutDetails, "applyCloseOutDetails");', label='complete_job tail')
# correction path (already closed): also apply scope details
rep('          const { data: settled } = await dbc.from("invoices").select("status,total,tip,amount_paid").eq("id", inv2.id).single();\n          const { data: jobNow } = await dbc.from("jobs").select("status,completed_on,final_price,disposal_site,tonnage").eq("id", job.id).single();\n          return ok({\n            corrected_existing_close_out: true,',
    '          const { data: settled } = await dbc.from("invoices").select("status,total,tip,amount_paid").eq("id", inv2.id).single();\n          const { data: jobNow } = await dbc.from("jobs").select("status,completed_on,final_price,disposal_site,tonnage").eq("id", job.id).single();\n          const warn2 = [];\n          const scope2 = await applyCloseOutDetails(dbc, env, job.id, a, completedOn2 ?? jobNow?.completed_on ?? detroitToday(), warn2);\n          return ok({\n            corrected_existing_close_out: true,\n            close_out: scope2,\n            still_missing: scope2?.still_missing ?? null,\n            ...warn2.length ? { warnings: warn2 } : {},', label='complete_job correction')

# ---- create_job: service_type required, lead_source enum, account ----
rep('        estimated_value: external_exports.number().positive().optional().describe("Expected price in dollars"),\n        lead_source: external_exports.string().optional().describe("How this job came in, e.g. \'referral\', \'Facebook\'")\n      }\n    },\n    guarded(async (a) => {\n      const { data: cust, error: cErr } = await dbc.from("customers").select("id,name,address,city").eq("id", a.customer_id).maybeSingle();',
    '        estimated_value: external_exports.number().positive().optional().describe("Expected price in dollars"),\n        lead_source: external_exports.enum(LEAD_SOURCES).optional().describe("How this job came in. Inherits the customer\'s lead_source when omitted; \'unknown\' is allowed but reported"),\n        service_type: external_exports.enum(["single_item", "furniture", "appliance", "mattress", "hot_tub", "garage_cleanout", "basement_cleanout", "estate_cleanout", "whole_home_cleanout", "yard_waste", "construction_debris", "demo", "commercial_cleanout", "property_turnover", "other"]).describe("REQUIRED service line"),\n        account_id: external_exports.string().uuid().optional().describe("Commercial account this job belongs to"),\n        job_kind: external_exports.enum(["customer", "internal"]).default("customer").describe("internal = dump run / shop time: carries costs, excluded from job counts"),\n        hauling_unit: external_exports.enum(["truck_bed", "trailer_6x12", "dumpster", "multiple"]).optional(),\n        load_fraction: external_exports.number().min(0).optional().describe("Expected trailer loads")\n      }\n    },\n    guarded(async (a) => {\n      const { data: cust, error: cErr } = await dbc.from("customers").select("id,name,address,city").eq("id", a.customer_id).maybeSingle();', label='create_job schema')
rep('        estimated_value: a.estimated_value ?? null,\n        lead_source: a.lead_source ?? null,\n        created_by: env.OWNER_USER_ID\n      }).select("id,title,status,service,scheduled_start,address,estimated_value").single();',
    '        estimated_value: a.estimated_value ?? null,\n        lead_source: a.lead_source ?? null,\n        service_type: a.service_type,\n        account_id: a.account_id ?? null,\n        job_kind: a.job_kind ?? "customer",\n        hauling_unit: a.hauling_unit ?? null,\n        load_fraction: a.load_fraction ?? null,\n        created_by: env.OWNER_USER_ID\n      }).select("id,title,status,service,scheduled_start,address,estimated_value,service_type,lead_source").single();', label='create_job insert')
rep('        status: job.status,\n        scheduled_start: job.scheduled_start,\n        address: job.address,\n        estimated_value: job.estimated_value === null ? null : Number(job.estimated_value)\n      });',
    '        status: job.status,\n        scheduled_start: job.scheduled_start,\n        address: job.address,\n        service_type: job.service_type,\n        lead_source: job.lead_source,\n        estimated_value: job.estimated_value === null ? null : Number(job.estimated_value)\n      });', label='create_job output')

# ---- update_job: new fields ----
rep('        notes: external_exports.string().optional().describe("Adds a note to the job\'s notes feed (doesn\'t overwrite anything)"),\n        cancel_linked_quote: external_exports.boolean().optional().describe("When cancelling: true also cancels the accepted quote, false keeps it")\n      }\n    },',
    '        notes: external_exports.string().optional().describe("Adds a note to the job\'s notes feed (doesn\'t overwrite anything)"),\n        cancel_linked_quote: external_exports.boolean().optional().describe("When cancelling: true also cancels the accepted quote, false keeps it"),\n        cancel_reason: external_exports.enum(["customer_cancelled", "no_show", "price", "scheduling", "weather", "hazmat_scope", "went_with_competitor", "other"]).optional().describe("Required when status = cancelled"),\n        service_type: external_exports.enum(["single_item", "furniture", "appliance", "mattress", "hot_tub", "garage_cleanout", "basement_cleanout", "estate_cleanout", "whole_home_cleanout", "yard_waste", "construction_debris", "demo", "commercial_cleanout", "property_turnover", "other"]).optional(),\n        job_kind: external_exports.enum(["customer", "internal"]).optional(),\n        is_test: external_exports.boolean().optional().describe("Test record \\u2014 excluded from every report"),\n        account_id: external_exports.string().uuid().optional(),\n        internal_notes: external_exports.string().optional().describe("Never shown to the customer"),\n        hauling_unit: external_exports.enum(["truck_bed", "trailer_6x12", "dumpster", "multiple"]).optional(),\n        load_fraction: external_exports.number().min(0).optional(),\n        crew_size: external_exports.number().int().optional(),\n        referred_by_customer_id: external_exports.string().uuid().optional()\n      }\n    },', label='update_job schema')
rep('      for (const k of ["title", "description", "address", "status", "service", "lead_source", "estimated_value", "final_price", "disposal_site", "tonnage", "completed_on"])\n        if (fields[k] !== void 0) patch[k] = fields[k];',
    '      for (const k of ["title", "description", "address", "status", "service", "lead_source", "estimated_value", "final_price", "disposal_site", "tonnage", "completed_on", "cancel_reason", "service_type", "job_kind", "is_test", "account_id", "internal_notes", "hauling_unit", "load_fraction", "crew_size", "referred_by_customer_id"])\n        if (fields[k] !== void 0) patch[k] = fields[k];\n      if (patch.status === "cancelled" && !patch.cancel_reason && !job.cancel_reason) return fail("bad_input", "cancel_reason is required when cancelling (customer_cancelled, no_show, price, scheduling, weather, hazmat_scope, went_with_competitor, other).");', label='update_job patch')

# ---- update_quote_status: loss reason + service_type on the created job ----
rep('        status: external_exports.enum(["sent", "accepted", "declined", "expired", "cancelled"]).describe("New status")\n      }\n    },\n    guarded(async ({ quote_id, quote_number, status }) => {',
    '        status: external_exports.enum(["sent", "accepted", "declined", "expired", "cancelled"]).describe("New status"),\n        loss_reason: external_exports.enum(["price_too_high", "went_with_competitor", "did_it_themselves", "city_bulk_pickup", "timing_scheduling", "scope_changed", "no_response_ghosted", "hazmat_or_out_of_scope", "deposit_required", "other"]).optional().describe("REQUIRED for declined/expired. no_response_ghosted is valid"),\n        competitor_name: external_exports.string().optional(),\n        competitor_price: external_exports.number().min(0).optional()\n      }\n    },\n    guarded(async ({ quote_id, quote_number, status, loss_reason, competitor_name, competitor_price }) => {\n      if ((status === "declined" || status === "expired") && !loss_reason)\n        return fail("bad_input", "loss_reason is required when a quote is declined or expired: price_too_high, went_with_competitor, did_it_themselves, city_bulk_pickup, timing_scheduling, scope_changed, no_response_ghosted, hazmat_or_out_of_scope, deposit_required, other.");', label='update_quote_status schema')
rep('      let q = dbc.from("estimates").select("id,estimate_number,status,total,customer_id,job_id,line_item,description,scheduled_start,customers(id,name,address,city),estimate_items(description,unit_price)").is("deleted_at", null);\n      q = quote_id ? q.eq("id", quote_id) : q.eq("estimate_number", quote_number);',
    '      let q = dbc.from("estimates").select("id,estimate_number,status,total,customer_id,job_id,line_item,description,scheduled_start,service_type,account_id,is_test,customers(id,name,address,city),estimate_items(description,unit_price)").is("deleted_at", null);\n      q = quote_id ? q.eq("id", quote_id) : q.eq("estimate_number", quote_number);', label='update_quote_status select')
rep('      const patch = { status };\n      if (status === "accepted") patch.accepted_at = (/* @__PURE__ */ new Date()).toISOString();\n      if (status === "declined") patch.declined_at = (/* @__PURE__ */ new Date()).toISOString();\n      const { error: upErr } = await dbc.from("estimates").update(patch).eq("id", est.id);',
    '      const patch = { status };\n      if (status === "accepted") patch.accepted_at = (/* @__PURE__ */ new Date()).toISOString();\n      if (status === "declined") patch.declined_at = (/* @__PURE__ */ new Date()).toISOString();\n      if (loss_reason) patch.loss_reason = loss_reason;\n      if (competitor_name) patch.competitor_name = competitor_name;\n      if (competitor_price !== void 0) patch.competitor_price = competitor_price;\n      const { error: upErr } = await dbc.from("estimates").update(patch).eq("id", est.id);', label='update_quote_status patch')
rep('          scheduled_start: est.scheduled_start ?? null,\n          estimated_value: Number(est.total),\n          created_by: env.OWNER_USER_ID\n        }).select("id,title,status,scheduled_start").single();',
    '          scheduled_start: est.scheduled_start ?? null,\n          estimated_value: Number(est.total),\n          service_type: est.service_type ?? "other",\n          quoted_price: Number(est.total),\n          account_id: est.account_id ?? null,\n          is_test: est.is_test ?? false,\n          created_by: env.OWNER_USER_ID\n        }).select("id,title,status,scheduled_start").single();', label='update_quote_status job insert')

# ---- create_quote: service_type + estimate fields ----
rep('        notes: external_exports.string().optional().describe("Internal note on the quote record \\u2014 NEVER shown to the customer"),\n        send: external_exports.boolean().default(false).describe("true marks it \'sent\' immediately; false leaves it as a draft"),',
    '        notes: external_exports.string().optional().describe("Internal note on the quote record \\u2014 NEVER shown to the customer"),\n        service_type: external_exports.enum(["single_item", "furniture", "appliance", "mattress", "hot_tub", "garage_cleanout", "basement_cleanout", "estate_cleanout", "whole_home_cleanout", "yard_waste", "construction_debris", "demo", "commercial_cleanout", "property_turnover", "other"]).optional().describe("Service line; carried into the job when accepted"),\n        hauling_unit: external_exports.enum(["truck_bed", "trailer_6x12", "dumpster", "multiple"]).optional(),\n        load_fraction: external_exports.number().min(0).optional().describe("Estimated trailer loads"),\n        est_weight_lbs: external_exports.number().min(0).optional(),\n        crew_size: external_exports.number().int().min(1).optional(),\n        deposit_required: external_exports.boolean().optional(),\n        deposit_amount: external_exports.number().min(0).optional(),\n        options: external_exports.array(external_exports.object({ label: external_exports.string(), scope: external_exports.string(), price: external_exports.number() })).optional().describe("Two-option quotes (A/B) \\u2014 tracked to see if they close better"),\n        lead_id: external_exports.string().uuid().optional().describe("The inquiry this quote answers"),\n        account_id: external_exports.string().uuid().optional(),\n        send: external_exports.boolean().default(false).describe("true marks it \'sent\' immediately; false leaves it as a draft"),', label='create_quote schema')
rep('        scheduled_start: a.scheduled_start ? parseDetroit(a.scheduled_start) : null,\n        tax_rate: 0,\n        created_by: env.OWNER_USER_ID\n      }).select("id,estimate_number,public_token,status,valid_until,scheduled_start,total").single();',
    '        scheduled_start: a.scheduled_start ? parseDetroit(a.scheduled_start) : null,\n        tax_rate: 0,\n        service_type: a.service_type ?? null,\n        hauling_unit: a.hauling_unit ?? null,\n        load_fraction: a.load_fraction ?? null,\n        est_weight_lbs: a.est_weight_lbs ?? null,\n        crew_size: a.crew_size ?? null,\n        deposit_required: a.deposit_required ?? false,\n        deposit_amount: a.deposit_amount ?? null,\n        options: a.options ?? null,\n        lead_id: a.lead_id ?? null,\n        account_id: a.account_id ?? null,\n        sent_at: a.send ? (/* @__PURE__ */ new Date()).toISOString() : null,\n        created_by: env.OWNER_USER_ID\n      }).select("id,estimate_number,public_token,status,valid_until,scheduled_start,total").single();', label='create_quote insert')

# ---- customers: segment / account / referral / do_not_contact ----
rep('        customer_type: external_exports.enum(["residential", "realtor", "property_manager", "contractor", "commercial"]).optional(),\n        is_high_value: external_exports.boolean().optional()\n      }\n    },\n    guarded(async (a) => {\n      const { customer_id, ...fields } = a;',
    '        customer_type: external_exports.enum(["residential", "realtor", "property_manager", "contractor", "commercial"]).optional(),\n        is_high_value: external_exports.boolean().optional(),\n        segment: external_exports.enum(["residential", "landlord", "property_manager", "realtor", "commercial", "nonprofit", "contractor", "other"]).optional(),\n        account_id: external_exports.string().uuid().optional(),\n        referred_by_customer_id: external_exports.string().uuid().optional(),\n        lead_source_detail: external_exports.string().optional(),\n        do_not_contact: external_exports.boolean().optional(),\n        is_test: external_exports.boolean().optional()\n      }\n    },\n    guarded(async (a) => {\n      const { customer_id, ...fields } = a;', label='update_customer schema')
rep('.select("id,name,phone,email,address,city,state,postal_code,tags,notes,internal_notes,lead_source,customer_type,is_high_value").single();\n      if (error51) return fail("db_error", error51.message);\n      await audit(dbc, "update_customer"',
    '.select("id,name,phone,email,address,city,state,postal_code,tags,notes,internal_notes,lead_source,customer_type,is_high_value,segment,account_id,referred_by_customer_id,do_not_contact").single();\n      if (error51) return fail("db_error", error51.message);\n      await audit(dbc, "update_customer"', label='update_customer select')
rep('        lead_source: external_exports.enum(LEAD_SOURCES).optional().describe("How they found the business"),\n        notes: external_exports.string().optional(),\n        allow_duplicate_name: external_exports.boolean().default(false).describe("Only after the user confirms this is a genuinely different person")',
    '        lead_source: external_exports.enum(LEAD_SOURCES).describe("REQUIRED: how they found the business (\'unknown\' if truly unknown)"),\n        segment: external_exports.enum(["residential", "landlord", "property_manager", "realtor", "commercial", "nonprofit", "contractor", "other"]).default("residential"),\n        referred_by_customer_id: external_exports.string().uuid().optional().describe("When lead_source is referral"),\n        lead_source_detail: external_exports.string().optional(),\n        account_id: external_exports.string().uuid().optional(),\n        notes: external_exports.string().optional(),\n        allow_duplicate_name: external_exports.boolean().default(false).describe("Only after the user confirms this is a genuinely different person")', label='create_customer schema')
rep('        lead_source: a.lead_source ?? null,\n        notes: a.notes ?? null,\n        created_by: env.OWNER_USER_ID\n      }).select(CUSTOMER_COLS).single();',
    '        lead_source: a.lead_source ?? "unknown",\n        segment: a.segment ?? "residential",\n        referred_by_customer_id: a.referred_by_customer_id ?? null,\n        lead_source_detail: a.lead_source_detail ?? null,\n        account_id: a.account_id ?? null,\n        notes: a.notes ?? null,\n        created_by: env.OWNER_USER_ID\n      }).select(CUSTOMER_COLS).single();', label='create_customer insert')

# ---- log_hours: activity ----
rep('        override_hourly_rate: external_exports.number().min(0).optional().describe("One-off rate instead of the worker\'s default"),\n        allow_duplicate: external_exports.boolean().default(false)',
    '        override_hourly_rate: external_exports.number().min(0).optional().describe("One-off rate instead of the worker\'s default"),\n        activity: external_exports.enum(["on_job", "drive", "dump_run", "site_visit_quote", "quoting_admin", "marketing", "bookkeeping", "other"]).default("on_job"),\n        allow_duplicate: external_exports.boolean().default(false)', label='log_hours schema')
rep('        job_id: a.job_id ?? null,\n        note: a.note ?? null,\n        created_by: env.OWNER_USER_ID\n      }).select("id,hours,rate,amount,worked_on,job_id").single();',
    '        job_id: a.job_id ?? null,\n        note: a.note ?? null,\n        activity: a.activity ?? "on_job",\n        created_by: env.OWNER_USER_ID\n      }).select("id,hours,rate,amount,worked_on,job_id").single();', label='log_hours insert')
# mark_hours_paid: tell the caller the payroll expense is generated now
rep('        entries_settled: rows.length,\n        hours_settled:', '        entries_settled: rows.length,\n        payroll_expense: "generated automatically from these entries \\u2014 do not add a separate payroll expense",\n        hours_settled:', label='mark_hours_paid note')

# ---- requests: intake ref map ----
rep('var INTAKE_REFS = {\n  facebook: "facebook", instagram: "instagram", google: "google",\n  nextdoor: "other", text: "referral", yard_sign: "yard_sign", website: "website"\n};\nfunction refToLeadSource(ref) {\n  const r = String(ref ?? "").trim().toLowerCase();\n  if (!r) return "website";',
    'var INTAKE_REFS = {\n  facebook: "meta_ads", instagram: "instagram", google: "google_business_profile",\n  nextdoor: "nextdoor", text: "other", yard_sign: "yard_sign_flyer", website: "website_direct", meta: "meta_ads", fb: "meta_ads", gbp: "google_business_profile"\n};\nfunction refToLeadSource(ref) {\n  const r = String(ref ?? "").trim().toLowerCase();\n  if (!r) return "website_direct";', label='INTAKE_REFS')
rep('  return UPDATABLE_LEAD_SOURCES.includes(r) ? r : "website";\n}', '  return UPDATABLE_LEAD_SOURCES.includes(r) ? r : "website_direct";\n}', label='refToLeadSource tail')

# ---- register the new module + server wiring ----
metrics = (S / 'metrics_tools.js').read_text()
rep('// src/server.ts\nfunction buildServer(env) {', metrics + '\n// src/server.ts\nfunction buildServer(env) {', label='module insert')
rep('  registerRequestTools(server, dbc, env);\n  return server;', '  registerRequestTools(server, dbc, env);\n  registerMetricsTools(server, dbc, env);\n  return server;', label='register call')
rep('{ name: "SJHC Connector", version: "2.0.0" }', '{ name: "SJHC Connector", version: "2.1.0" }', label='version')
rep("Start customer lookups with find_customer. After a write, report the record that came back rather than just confirming success.",
    "Start customer lookups with find_customer. After a write, report the record that came back rather than just confirming success. METRICS (2026-09): every new job needs service_type and a lead_source; every close-out should capture owner_hours, load_fraction and the dump ticket (complete_job returns still_missing); declined/expired quotes need loss_reason; helper pay is logged as hours (log_hours / helper_labor) and the payroll expense is generated when marked paid; owner pay is expense_class owner_draw, personal spend is personal \\u2014 both stay in the ledger and out of profit. Reports: pnl_report, unit_economics, owner_hourly, quote_win_rate, channel_roi, service_line_profitability, customer_metrics, pipeline_report, data_health_check, weekly_scorecard, monthly_close, full_time_readiness.", label='instructions')

(S / 'index.patched.js').write_text(src)
print("patched", orig_len, "->", len(src), "fails:", len(fails))
for f in fails: print(" -", f)
